CREATE TABLE [ods].[Aramark_OrderLineItems]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__Aramark_O__ETL_C__3AF91678] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__Aramark_O__ETL_U__3BED3AB1] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__Aramark_O__ETL_I__3CE15EEA] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemID] [int] NULL,
[SiteID] [int] NULL,
[SystemPOSID] [int] NULL,
[LocationID] [int] NULL,
[revenueCenterID] [int] NULL,
[revenueCenterPOSRef] [int] NULL,
[guestcheckId] [int] NULL,
[guestCheckLineItemID] [int] NULL,
[businessDate] [datetime] NULL,
[transdatetime] [datetime] NULL,
[detailType] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[recordPosRef] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[recordName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priceLevel] [int] NULL,
[voidflag] [int] NULL,
[genflag1] [int] NULL,
[lineCount] [int] NULL,
[lineTotal] [decimal] (8, 2) NULL,
[reportLineCount] [int] NULL,
[reportLineTotal] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[referenceInfo] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[referenceInfo2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[doNotShow] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterPosRef] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[daypartid] [int] NULL,
[reasoncodeposRef] [int] NULL,
[reasonName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[majorgroupPosRef] [int] NULL,
[majorgroupname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familygroupPosRef] [int] NULL,
[familygroupname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax1total] [decimal] (8, 2) NULL,
[tax2total] [decimal] (8, 2) NULL,
[tax3total] [decimal] (8, 2) NULL,
[tax4total] [decimal] (8, 2) NULL,
[tax5total] [decimal] (8, 2) NULL,
[tax6total] [decimal] (8, 2) NULL,
[tax7total] [decimal] (8, 2) NULL,
[tax8total] [decimal] (8, 2) NULL,
[dscMenuItemPosRef] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[revenueCenterName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[uwsid] [int] NULL
)
GO
ALTER TABLE [ods].[Aramark_OrderLineItems] ADD CONSTRAINT [PK__Aramark___7EF6BFCD7F1F3877] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
