CREATE TABLE [ods].[Aramark_OrderHeaders]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__Aramark_O__ETL_C__4576A4EB] DEFAULT (getdate()),
[ETL_UpdatedDate] [datetime] NOT NULL CONSTRAINT [DF__Aramark_O__ETL_U__466AC924] DEFAULT (getdate()),
[ETL_IsDeleted] [bit] NOT NULL CONSTRAINT [DF__Aramark_O__ETL_I__475EED5D] DEFAULT ((0)),
[ETL_DeletedDate] [datetime] NULL,
[ETL_DeltaHashKey] [binary] (32) NULL,
[ETL_SourceFileName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemID] [int] NULL,
[SiteID] [int] NULL,
[SystemPOSID] [int] NULL,
[LocationID] [int] NULL,
[revenueCenterID] [int] NULL,
[revenueCenterPOSRef] [int] NULL,
[guestcheckId] [int] NULL,
[orderTypePOSRef] [int] NULL,
[checkNum] [int] NULL,
[openBusinessDate] [datetime] NULL,
[closeBusinessDate] [datetime] NULL,
[openDatetime] [datetime] NULL,
[closeDatetime] [datetime] NULL,
[numGuests] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checkRef] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[checkTotal] [decimal] (8, 2) NULL,
[taxTotal] [decimal] (8, 2) NULL,
[taxExempt] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[voidTotal] [decimal] (8, 2) NULL,
[tipTotal] [decimal] (8, 2) NULL,
[managerVoidTotal] [decimal] (8, 2) NULL,
[returnTotal] [decimal] (8, 2) NULL,
[errorCorrectTotal] [decimal] (8, 2) NULL,
[xferStatus] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[xferToCheckNum] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[serviceChargeTotal] [decimal] (8, 2) NULL,
[discountTotal] [decimal] (8, 2) NULL,
[subTotal] [decimal] (8, 2) NULL,
[tax1total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax2total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax3total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax4total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax5total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax6total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax7total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[tax8total] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[revenueCenterName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [ods].[Aramark_OrderHeaders] ADD CONSTRAINT [PK__Aramark___7EF6BFCD5A11FA6F] PRIMARY KEY CLUSTERED  ([ETL_ID])
GO
